name: Publish package to NPM

on:
  workflow_dispatch:
    branches:
      - master
  push:
    paths:
      - 'src/**'
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Load Yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Setup git user
        run: |
          git config user.name "TheAsda"
          git config user.email "omega-faworit@yandex.ru"
      - name: Configure npm
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
      - name: Publish to NPM
        run: |
          yarn changeset version --snapshot pr
          yarn changeset publish --tag pr
        env:
          CI: true
      - name: Get released version
        id: version
        run: echo ::set-output name=version::$(node -p "require('./package.json').version")
      - name: Commit, tag and push changelog
        run: |
          git add CHANGELOG.md
          git add package.json
          git commit -m "Release v${{ steps.version.outputs.version }}"
          git tag v${{ steps.version.outputs.version }}
          git push --tags
